In [1]:
l = list(range(0,12))
l

listOdd = list(range(1, 13, 2))
listEven = list(range(0, 12, 2))
print(listOdd)
print(listEven)

#multiply the 2 lists
listProduct = []
for counter in range(0, len(listOdd)):
    listProduct.append(listOdd[counter] * listEven[counter])
print(listProduct)

[1, 3, 5, 7, 9, 11]
[0, 2, 4, 6, 8, 10]
[0, 6, 20, 42, 72, 110]


In [14]:
import numpy as np
arr1 = np.array(listOdd)
arr2 = np.array(listEven)
arr3 = arr1 * arr2
for counter in range(0, len(arr3)):
    print(arr1[counter], "*", arr2[counter], "=", arr3[counter])


1 * 0 = 0
3 * 2 = 6
5 * 4 = 20
7 * 6 = 42
9 * 8 = 72
11 * 10 = 110


In [15]:
print(type(arr3))

<class 'numpy.ndarray'>


In [25]:
#multi dim zeros array
zeros = np.zeros((2, 3, 5), dtype=int)
ones = np.ones((2, 3,5), dtype=int)
zeros + ones * 3

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [29]:
# use full
arrF5 = np.full((2, 3, 5), 13)
arrF5

array([[[13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13]],

       [[13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13]]])

In [32]:
arr6 = np.array(range(0,10))
print(type(arr6))

<class 'numpy.ndarray'>


In [52]:
np.eye(5, 3, -2)
np.random.randn(3, 5, 3)
arrNormal = np.random.normal(5, 11, 100)
arrNormal

array([  7.79946807,   5.20000142,  -3.45970918,  -6.15619559,
        14.91643212,  13.17528353,  -5.02768345,   8.62060741,
        17.88441781, -27.22358957,   9.34984562,  -6.7162332 ,
         5.37627842,   8.58833274,   3.74170162,  -0.75882315,
         2.38276413,  -5.23964432,   6.40454564,  15.61287819,
       -34.69378231,  13.63922616,  -9.42078586,  -6.63878505,
        16.81165797,  -9.22272958,  -7.43339587,  -1.37942604,
        -4.78937268,  -0.38090065,  20.88145119,  17.78666174,
         5.66209569,  20.89851523,  11.23392115,  19.23220638,
        -4.52893397,   0.61721524,  -7.11805251, -18.74681664,
        -3.90906489,   2.41233015,   0.20599687, -21.87176781,
         0.59920765,  20.75268528,   7.34933106,  -1.84849863,
       -14.66316675,   9.50593319,  19.00892499,   8.60706168,
        -8.61903436,   0.68526683,  18.94617494,  17.72241752,
        -5.08625817,   5.26595988,  13.69658543,  24.67173405,
        20.10121937,  11.13331197,   5.19957729,   7.28

In [63]:
arrNormal.reshape((10, 5, 2)).ndim

3