In [12]:
l = list(range(0,12))
l

listOdd = list(range(1, 13, 2))
listEven = list(range(0, 12, 2))
print(listOdd)
print(listEven)

#multiply the 2 lists
listProduct = []
for counter in range(0, len(listOdd)):
    listProduct.append(listOdd[counter] * listEven[counter])
print(listProduct)

[1, 3, 5, 7, 9, 11]
[0, 2, 4, 6, 8, 10]
[0, 6, 20, 42, 72, 110]


In [14]:
import numpy as np
arr1 = np.array(listOdd)
arr2 = np.array(listEven)
arr3 = arr1 * arr2
for counter in range(0, len(arr3)):
    print(arr1[counter], "*", arr2[counter], "=", arr3[counter])


1 * 0 = 0
3 * 2 = 6
5 * 4 = 20
7 * 6 = 42
9 * 8 = 72
11 * 10 = 110


In [15]:
print(type(arr3))

<class 'numpy.ndarray'>


In [25]:
#multi dim zeros array
zeros = np.zeros((2, 3, 5), dtype=int)
ones = np.ones((2, 3,5), dtype=int)
zeros + ones * 3

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [29]:
# use full
arrF5 = np.full((2, 3, 5), 13)
arrF5

array([[[13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13]],

       [[13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13]]])

In [32]:
arr6 = np.array(range(0,10))
print(type(arr6))

<class 'numpy.ndarray'>


In [40]:
np.eye(5, 3, -2)
np.random.randn(3, 5, 3)
np.random.normal(5, 11, 100)


array([ 3.26577596e+00,  1.42555142e+00,  9.64264219e+00, -1.77892555e+00,
        8.15032540e+00, -1.24274733e-02,  1.50187082e+00,  4.81013824e+00,
        9.43414403e+00, -9.03389598e+00,  2.55410885e+01, -2.03266383e+00,
        2.20035343e+01,  1.26377541e+01,  2.75781156e+01, -1.93270348e+01,
        3.08143135e+01,  9.19801676e+00,  7.42023748e+00,  5.27490556e+00,
       -8.57045390e-01, -1.54729343e+01,  2.04568516e+01,  1.39577997e+01,
       -6.15490710e+00,  4.07422391e+00,  3.80676959e+00, -1.97748378e+01,
        2.01888338e+01,  9.46007468e+00,  2.73468925e+00, -1.11051609e+01,
        4.09242417e+00, -2.97779685e+00, -9.93935883e+00,  1.42373852e+01,
       -6.57571144e+00,  1.80185132e+01, -1.30637552e+01,  9.61911969e+00,
        2.67557391e+00, -4.77774588e+00, -9.36982663e-01,  5.99903967e+00,
        3.39584080e+00,  4.01178402e+00, -3.21786970e+00,  7.53801522e-01,
        1.50069154e+01, -4.39203042e+00, -8.31975048e+00, -7.47724547e+00,
       -7.48817744e+00,  

In [47]:
arrF5.size

30