In [7]:
import numpy as np
arr1 = np.arange(10, 110, 10).reshape(5, 2)
arr2 = np.arange(15, 215, 20).reshape(5, 2)
arr3 = np.concatenate([arr1 , arr2], 1)
arr3

array([[ 10,  20,  15,  35],
       [ 30,  40,  55,  75],
       [ 50,  60,  95, 115],
       [ 70,  80, 135, 155],
       [ 90, 100, 175, 195]])

In [11]:
np.hsplit(arr3, 1)

[array([[ 10,  20,  15,  35],
        [ 30,  40,  55,  75],
        [ 50,  60,  95, 115],
        [ 70,  80, 135, 155],
        [ 90, 100, 175, 195]])]

In [4]:
np.vsplit(arr3, [2, 3])

[array([[10, 20, 15, 35],
        [30, 40, 55, 75]]),
 array([[ 50,  60,  95, 115]]),
 array([[ 70,  80, 135, 155],
        [ 90, 100, 175, 195]])]

In [16]:
#slicing
arr3[2:4,2:4] = np.array([[11, 12],
                          [21,22]])
arr3

array([[ 10,  20,  15,  35],
       [ 30,  40,  55,  75],
       [ 50,  60,  11,  12],
       [ 70,  80,  21,  22],
       [ 90, 100, 175, 195]])

In [27]:
arr4 = np.array(np.arange(10, 20, 2))
np.split(arr3, [2,4])
arr4[2]


14

In [28]:
arr3

array([[ 10,  20,  15,  35],
       [ 30,  40,  55,  75],
       [ 50,  60,  11,  12],
       [ 70,  80,  21,  22],
       [ 90, 100, 175, 195]])

In [33]:
arr3[:3, 2:] = np.array([[121, 122],
                         [287, 426],
                         [891, 41]])
arr3

array([[ 10,  20, 121, 122],
       [ 30,  40, 287, 426],
       [ 50,  60, 891,  41],
       [ 70,  80,  21,  22],
       [ 90, 100, 175, 195]])

In [37]:
arr3[:, 3] = [11, 12, 13, 14, 15]
arr3

array([[ 10,  20, 121,  11],
       [ 30,  40, 287,  12],
       [ 50,  60, 891,  13],
       [ 70,  80,  21,  14],
       [ 90, 100, 175,  15]])

In [42]:
indices = [1,4]
arr4[indices]

array([12, 18])

In [43]:
arrZeroes = np.zeros((10, 10))
arrZeroes

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
for row in range(len(arrZeroes)):
    for col in range(len(arrZeroes[0])):
        arrZeroes[row, col] = row+col

arrZeroes

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])

In [50]:
np.mean(arr3)

105.5